version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: mini-order
    environment:
      POSTGRES_DB: mini_order
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5433:5432"
    volumes:
      - ./data:/docker-entrypoint-initdb.d
